language: csharp
mono: none
dotnet: 8.0
os: windows

branches:
  only:
    - main

install:
  - dotnet restore

script:
  - dotnet build -c Release
  - dotnet test -c Release

after_success:
  - dotnet pack ./src/com.Messente.Api/com.Messente.Api.csproj -o ./output -c Release --no-build

deploy:
  provider: script
  script: dotnet nuget push ./output/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
  on:
    tags: true
