/*
 * Messente API
 *
 * [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber, WhatsApp and Telegram messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: messente@messente.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = com.Messente.Api.Client.OpenAPIDateConverter;
using System.Reflection;

namespace com.Messente.Api.Model
{
    /// <summary>
    /// BulkOmniMessageCreateSuccessResponseMessagesInner
    /// </summary>
    [JsonConverter(typeof(BulkOmniMessageCreateSuccessResponseMessagesInnerJsonConverter))]
    [DataContract(Name = "BulkOmniMessageCreateSuccessResponse_messages_inner")]
    public partial class BulkOmniMessageCreateSuccessResponseMessagesInner : AbstractOpenAPISchema, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BulkOmniMessageCreateSuccessResponseMessagesInner" /> class
        /// with the <see cref="OmniMessageCreateSuccessResponse" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of OmniMessageCreateSuccessResponse.</param>
        public BulkOmniMessageCreateSuccessResponseMessagesInner(OmniMessageCreateSuccessResponse actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BulkOmniMessageCreateSuccessResponseMessagesInner" /> class
        /// with the <see cref="ErrorOmnichannel" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ErrorOmnichannel.</param>
        public BulkOmniMessageCreateSuccessResponseMessagesInner(ErrorOmnichannel actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(ErrorOmnichannel))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(OmniMessageCreateSuccessResponse))
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: ErrorOmnichannel, OmniMessageCreateSuccessResponse");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `OmniMessageCreateSuccessResponse`. If the actual instance is not `OmniMessageCreateSuccessResponse`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of OmniMessageCreateSuccessResponse</returns>
        public OmniMessageCreateSuccessResponse GetOmniMessageCreateSuccessResponse()
        {
            return (OmniMessageCreateSuccessResponse)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ErrorOmnichannel`. If the actual instance is not `ErrorOmnichannel`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ErrorOmnichannel</returns>
        public ErrorOmnichannel GetErrorOmnichannel()
        {
            return (ErrorOmnichannel)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BulkOmniMessageCreateSuccessResponseMessagesInner {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, BulkOmniMessageCreateSuccessResponseMessagesInner.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of BulkOmniMessageCreateSuccessResponseMessagesInner
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of BulkOmniMessageCreateSuccessResponseMessagesInner</returns>
        public static BulkOmniMessageCreateSuccessResponseMessagesInner FromJson(string jsonString)
        {
            BulkOmniMessageCreateSuccessResponseMessagesInner newBulkOmniMessageCreateSuccessResponseMessagesInner = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newBulkOmniMessageCreateSuccessResponseMessagesInner;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ErrorOmnichannel).GetProperty("AdditionalProperties") == null)
                {
                    newBulkOmniMessageCreateSuccessResponseMessagesInner = new BulkOmniMessageCreateSuccessResponseMessagesInner(JsonConvert.DeserializeObject<ErrorOmnichannel>(jsonString, BulkOmniMessageCreateSuccessResponseMessagesInner.SerializerSettings));
                }
                else
                {
                    newBulkOmniMessageCreateSuccessResponseMessagesInner = new BulkOmniMessageCreateSuccessResponseMessagesInner(JsonConvert.DeserializeObject<ErrorOmnichannel>(jsonString, BulkOmniMessageCreateSuccessResponseMessagesInner.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ErrorOmnichannel");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ErrorOmnichannel: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(OmniMessageCreateSuccessResponse).GetProperty("AdditionalProperties") == null)
                {
                    newBulkOmniMessageCreateSuccessResponseMessagesInner = new BulkOmniMessageCreateSuccessResponseMessagesInner(JsonConvert.DeserializeObject<OmniMessageCreateSuccessResponse>(jsonString, BulkOmniMessageCreateSuccessResponseMessagesInner.SerializerSettings));
                }
                else
                {
                    newBulkOmniMessageCreateSuccessResponseMessagesInner = new BulkOmniMessageCreateSuccessResponseMessagesInner(JsonConvert.DeserializeObject<OmniMessageCreateSuccessResponse>(jsonString, BulkOmniMessageCreateSuccessResponseMessagesInner.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("OmniMessageCreateSuccessResponse");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into OmniMessageCreateSuccessResponse: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + String.Join(",", matchedTypes));
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newBulkOmniMessageCreateSuccessResponseMessagesInner;
        }


        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for BulkOmniMessageCreateSuccessResponseMessagesInner
    /// </summary>
    public class BulkOmniMessageCreateSuccessResponseMessagesInnerJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(BulkOmniMessageCreateSuccessResponseMessagesInner).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.StartObject:
                    return BulkOmniMessageCreateSuccessResponseMessagesInner.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return BulkOmniMessageCreateSuccessResponseMessagesInner.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
