/* 
 * Messente API
 *
 * [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber, WhatsApp and Telegram messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * OpenAPI spec version: 1.2.0
 * Contact: messente@messente.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = com.Messente.Api.Client.OpenAPIDateConverter;

namespace com.Messente.Api.Model
{
    /// <summary>
    /// A container for phone numbers
    /// </summary>
    [DataContract]
    public partial class NumbersToInvestigate :  IEquatable<NumbersToInvestigate>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NumbersToInvestigate" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected NumbersToInvestigate() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="NumbersToInvestigate" /> class.
        /// </summary>
        /// <param name="numbers">Array of phone numbers (required).</param>
        public NumbersToInvestigate(List<string> numbers = default(List<string>))
        {
            // to ensure "numbers" is required (not null)
            if (numbers == null)
            {
                throw new InvalidDataException("numbers is a required property for NumbersToInvestigate and cannot be null");
            }
            else
            {
                this.Numbers = numbers;
            }
        }
        
        /// <summary>
        /// Array of phone numbers
        /// </summary>
        /// <value>Array of phone numbers</value>
        [DataMember(Name="numbers", EmitDefaultValue=false)]
        public List<string> Numbers { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class NumbersToInvestigate {\n");
            sb.Append("  Numbers: ").Append(Numbers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as NumbersToInvestigate);
        }

        /// <summary>
        /// Returns true if NumbersToInvestigate instances are equal
        /// </summary>
        /// <param name="input">Instance of NumbersToInvestigate to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NumbersToInvestigate input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Numbers == input.Numbers ||
                    this.Numbers != null &&
                    this.Numbers.SequenceEqual(input.Numbers)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Numbers != null)
                    hashCode = hashCode * 59 + this.Numbers.GetHashCode();
                return hashCode;
            }
        }
    }

}
