/*
 * Messente API
 *
 * [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber and WhatsApp messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: messente@messente.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = com.Messente.Api.Client.OpenAPIDateConverter;
using System.Reflection;

namespace com.Messente.Api.Model
{
    /// <summary>
    /// OmnimessageMessagesInner
    /// </summary>
    [JsonConverter(typeof(OmnimessageMessagesInnerJsonConverter))]
    [DataContract(Name = "Omnimessage_messages_inner")]
    public partial class OmnimessageMessagesInner : AbstractOpenAPISchema, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OmnimessageMessagesInner" /> class
        /// with the <see cref="Viber" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of Viber.</param>
        public OmnimessageMessagesInner(Viber actualInstance)
        {
            IsNullable = false;
            SchemaType= "anyOf";
            ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OmnimessageMessagesInner" /> class
        /// with the <see cref="SMS" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SMS.</param>
        public OmnimessageMessagesInner(SMS actualInstance)
        {
            IsNullable = false;
            SchemaType= "anyOf";
            ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OmnimessageMessagesInner" /> class
        /// with the <see cref="WhatsApp" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of WhatsApp.</param>
        public OmnimessageMessagesInner(WhatsApp actualInstance)
        {
            IsNullable = false;
            SchemaType= "anyOf";
            ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OmnimessageMessagesInner" /> class
        /// with the <see cref="Rcs" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of Rcs.</param>
        public OmnimessageMessagesInner(Rcs actualInstance)
        {
            IsNullable = false;
            SchemaType= "anyOf";
            ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(Rcs))
                {
                    _actualInstance = value;
                }
                else if (value.GetType() == typeof(SMS))
                {
                    _actualInstance = value;
                }
                else if (value.GetType() == typeof(Viber))
                {
                    _actualInstance = value;
                }
                else if (value.GetType() == typeof(WhatsApp))
                {
                    _actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: Rcs, SMS, Viber, WhatsApp");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `Viber`. If the actual instance is not `Viber`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of Viber</returns>
        public Viber GetViber()
        {
            return (Viber)ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `SMS`. If the actual instance is not `SMS`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SMS</returns>
        public SMS GetSMS()
        {
            return (SMS)ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `WhatsApp`. If the actual instance is not `WhatsApp`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of WhatsApp</returns>
        public WhatsApp GetWhatsApp()
        {
            return (WhatsApp)ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `Rcs`. If the actual instance is not `Rcs`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of Rcs</returns>
        public Rcs GetRcs()
        {
            return (Rcs)ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class OmnimessageMessagesInner {\n");
            sb.Append("  ActualInstance: ").Append(ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(ActualInstance, OmnimessageMessagesInner.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of OmnimessageMessagesInner
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of OmnimessageMessagesInner</returns>
        public static OmnimessageMessagesInner FromJson(string jsonString)
        {
            OmnimessageMessagesInner newOmnimessageMessagesInner = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newOmnimessageMessagesInner;
            }

            try
            {
                newOmnimessageMessagesInner = new OmnimessageMessagesInner(JsonConvert.DeserializeObject<Rcs>(jsonString, OmnimessageMessagesInner.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newOmnimessageMessagesInner;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into Rcs: {1}", jsonString, exception.ToString()));
            }

            try
            {
                newOmnimessageMessagesInner = new OmnimessageMessagesInner(JsonConvert.DeserializeObject<SMS>(jsonString, OmnimessageMessagesInner.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newOmnimessageMessagesInner;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SMS: {1}", jsonString, exception.ToString()));
            }

            try
            {
                newOmnimessageMessagesInner = new OmnimessageMessagesInner(JsonConvert.DeserializeObject<Viber>(jsonString, OmnimessageMessagesInner.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newOmnimessageMessagesInner;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into Viber: {1}", jsonString, exception.ToString()));
            }

            try
            {
                newOmnimessageMessagesInner = new OmnimessageMessagesInner(JsonConvert.DeserializeObject<WhatsApp>(jsonString, OmnimessageMessagesInner.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newOmnimessageMessagesInner;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into WhatsApp: {1}", jsonString, exception.ToString()));
            }

            // no match found, throw an exception
            throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for OmnimessageMessagesInner
    /// </summary>
    public class OmnimessageMessagesInnerJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(OmnimessageMessagesInner).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.StartObject:
                    return OmnimessageMessagesInner.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return OmnimessageMessagesInner.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
