/*
 * Messente API
 *
 * [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber and WhatsApp messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: messente@messente.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = com.Messente.Api.Client.OpenAPIDateConverter;

namespace com.Messente.Api.Model
{
    /// <summary>
    /// RCS media object.
    /// </summary>
    [DataContract(Name = "RcsMedia")]
    public partial class RcsMedia : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Height
        /// </summary>
        [DataMember(Name = "height", IsRequired = true, EmitDefaultValue = true)]
        public RcsMediaHeight Height { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="RcsMedia" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RcsMedia()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="RcsMedia" /> class.
        /// </summary>
        /// <param name="height">height (required).</param>
        /// <param name="contentInfo">contentInfo (required).</param>
        public RcsMedia(RcsMediaHeight height = default(RcsMediaHeight), RcsContentInfo contentInfo = default(RcsContentInfo))
        {
            this.Height = height;
            // to ensure "contentInfo" is required (not null)
            if (contentInfo == null)
            {
                throw new ArgumentNullException("contentInfo is a required property for RcsMedia and cannot be null");
            }
            this.ContentInfo = contentInfo;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Gets or Sets ContentInfo
        /// </summary>
        [DataMember(Name = "content_info", IsRequired = true, EmitDefaultValue = true)]
        public RcsContentInfo ContentInfo { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RcsMedia {\n");
            sb.Append("  Height: ").Append(Height).Append("\n");
            sb.Append("  ContentInfo: ").Append(ContentInfo).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
