/*
 * Messente API
 *
 * [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber and WhatsApp messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: messente@messente.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = com.Messente.Api.Client.OpenAPIDateConverter;

namespace com.Messente.Api.Model
{
    /// <summary>
    /// Action to open a URL in a browser.
    /// </summary>
    [DataContract(Name = "RcsOpenUrlAction")]
    public partial class RcsOpenUrlAction : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Application
        /// </summary>
        [DataMember(Name = "application", IsRequired = true, EmitDefaultValue = true)]
        public RcsOpenUrlApplication Application { get; set; }

        /// <summary>
        /// Gets or Sets WebviewViewMode
        /// </summary>
        [DataMember(Name = "webview_view_mode", IsRequired = true, EmitDefaultValue = true)]
        public RcsWebviewViewMode WebviewViewMode { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="RcsOpenUrlAction" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RcsOpenUrlAction()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="RcsOpenUrlAction" /> class.
        /// </summary>
        /// <param name="url">The URL to open. (required).</param>
        /// <param name="description">A description of the URL being opened. (required).</param>
        /// <param name="application">application (required).</param>
        /// <param name="webviewViewMode">webviewViewMode (required).</param>
        public RcsOpenUrlAction(string url = default(string), string description = default(string), RcsOpenUrlApplication application = default(RcsOpenUrlApplication), RcsWebviewViewMode webviewViewMode = default(RcsWebviewViewMode))
        {
            // to ensure "url" is required (not null)
            if (url == null)
            {
                throw new ArgumentNullException("url is a required property for RcsOpenUrlAction and cannot be null");
            }
            this.Url = url;
            // to ensure "description" is required (not null)
            if (description == null)
            {
                throw new ArgumentNullException("description is a required property for RcsOpenUrlAction and cannot be null");
            }
            this.Description = description;
            this.Application = application;
            this.WebviewViewMode = webviewViewMode;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// The URL to open.
        /// </summary>
        /// <value>The URL to open.</value>
        [DataMember(Name = "url", IsRequired = true, EmitDefaultValue = true)]
        public string Url { get; set; }

        /// <summary>
        /// A description of the URL being opened.
        /// </summary>
        /// <value>A description of the URL being opened.</value>
        [DataMember(Name = "description", IsRequired = true, EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RcsOpenUrlAction {\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Application: ").Append(Application).Append("\n");
            sb.Append("  WebviewViewMode: ").Append(WebviewViewMode).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Url (string) maxLength
            if (this.Url != null && this.Url.Length > 2048)
            {
                yield return new ValidationResult("Invalid value for Url, length must be less than 2048.", new [] { "Url" });
            }

            yield break;
        }
    }

}
