/*
 * Messente API
 *
 * [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber and WhatsApp messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: messente@messente.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = com.Messente.Api.Client.OpenAPIDateConverter;

namespace com.Messente.Api.Model
{
    /// <summary>
    /// RCS standalone card object.
    /// </summary>
    [DataContract(Name = "RcsStandaloneCard")]
    public partial class RcsStandaloneCard : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets CardOrientation
        /// </summary>
        [DataMember(Name = "card_orientation", IsRequired = true, EmitDefaultValue = true)]
        public RcsCardOrientation CardOrientation { get; set; }

        /// <summary>
        /// Gets or Sets ThumbnailImageAlignment
        /// </summary>
        [DataMember(Name = "thumbnail_image_alignment", IsRequired = true, EmitDefaultValue = true)]
        public RcsImageAlignment ThumbnailImageAlignment { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="RcsStandaloneCard" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RcsStandaloneCard()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="RcsStandaloneCard" /> class.
        /// </summary>
        /// <param name="cardOrientation">cardOrientation (required).</param>
        /// <param name="thumbnailImageAlignment">thumbnailImageAlignment (required).</param>
        /// <param name="cardContent">cardContent (required).</param>
        public RcsStandaloneCard(RcsCardOrientation cardOrientation = default(RcsCardOrientation), RcsImageAlignment thumbnailImageAlignment = default(RcsImageAlignment), RcsCardContent cardContent = default(RcsCardContent))
        {
            this.CardOrientation = cardOrientation;
            this.ThumbnailImageAlignment = thumbnailImageAlignment;
            // to ensure "cardContent" is required (not null)
            if (cardContent == null)
            {
                throw new ArgumentNullException("cardContent is a required property for RcsStandaloneCard and cannot be null");
            }
            this.CardContent = cardContent;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Gets or Sets CardContent
        /// </summary>
        [DataMember(Name = "card_content", IsRequired = true, EmitDefaultValue = true)]
        public RcsCardContent CardContent { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RcsStandaloneCard {\n");
            sb.Append("  CardOrientation: ").Append(CardOrientation).Append("\n");
            sb.Append("  ThumbnailImageAlignment: ").Append(ThumbnailImageAlignment).Append("\n");
            sb.Append("  CardContent: ").Append(CardContent).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
