/*
 * Messente API
 *
 * [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber, WhatsApp and Telegram messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: messente@messente.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = com.Messente.Api.Client.OpenAPIDateConverter;

namespace com.Messente.Api.Model
{
    /// <summary>
    /// A container for statistics reports
    /// </summary>
    [DataContract(Name = "StatisticsReportSuccess")]
    public partial class StatisticsReportSuccess : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StatisticsReportSuccess" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected StatisticsReportSuccess()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="StatisticsReportSuccess" /> class.
        /// </summary>
        /// <param name="reports">Array of report objects (required).</param>
        public StatisticsReportSuccess(List<StatisticsReport> reports = default(List<StatisticsReport>))
        {
            // to ensure "reports" is required (not null)
            if (reports == null)
            {
                throw new ArgumentNullException("reports is a required property for StatisticsReportSuccess and cannot be null");
            }
            this.Reports = reports;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Array of report objects
        /// </summary>
        /// <value>Array of report objects</value>
        [DataMember(Name = "reports", IsRequired = true, EmitDefaultValue = true)]
        public List<StatisticsReport> Reports { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class StatisticsReportSuccess {\n");
            sb.Append("  Reports: ").Append(Reports).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
