/* 
 * Messente API
 *
 * [Messente](https://messente.com) is a global provider of messaging and user verification services. Use Messente API library to send and receive SMS, Viber and WhatsApp messages, blacklist phone numbers to make sure you're not sending any unwanted messages, manage contacts and groups.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * OpenAPI spec version: 1.0.1
 * Contact: messente@messente.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = com.Messente.Api.Client.OpenAPIDateConverter;

namespace com.Messente.Api.Model
{
    /// <summary>
    /// Whether to store message content as is (plaintext), as a hashed value (sha256) or not at all (nostore)
    /// </summary>
    /// <value>Whether to store message content as is (plaintext), as a hashed value (sha256) or not at all (nostore)</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum TextStore
    {
        /// <summary>
        /// Enum Nostore for value: nostore
        /// </summary>
        [EnumMember(Value = "nostore")]
        Nostore = 1,

        /// <summary>
        /// Enum Plaintext for value: plaintext
        /// </summary>
        [EnumMember(Value = "plaintext")]
        Plaintext = 2,

        /// <summary>
        /// Enum Sha256 for value: sha256
        /// </summary>
        [EnumMember(Value = "sha256")]
        Sha256 = 3

    }

}
