/*
 * Messente API
 *
 * [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber, WhatsApp and Telegram messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: messente@messente.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = com.Messente.Api.Client.OpenAPIDateConverter;

namespace com.Messente.Api.Model
{
    /// <summary>
    /// Whatsapp Cloud API list of templates response
    /// </summary>
    [DataContract(Name = "WhatsappListTemplatesResponse")]
    public partial class WhatsappListTemplatesResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WhatsappListTemplatesResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WhatsappListTemplatesResponse()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="WhatsappListTemplatesResponse" /> class.
        /// </summary>
        /// <param name="templates">List of templates (required).</param>
        /// <param name="paging">paging (required).</param>
        public WhatsappListTemplatesResponse(List<WhatsappTemplateResponse> templates = default(List<WhatsappTemplateResponse>), WhatsappPagination paging = default(WhatsappPagination))
        {
            // to ensure "templates" is required (not null)
            if (templates == null)
            {
                throw new ArgumentNullException("templates is a required property for WhatsappListTemplatesResponse and cannot be null");
            }
            this.Templates = templates;
            // to ensure "paging" is required (not null)
            if (paging == null)
            {
                throw new ArgumentNullException("paging is a required property for WhatsappListTemplatesResponse and cannot be null");
            }
            this.Paging = paging;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// List of templates
        /// </summary>
        /// <value>List of templates</value>
        [DataMember(Name = "templates", IsRequired = true, EmitDefaultValue = true)]
        public List<WhatsappTemplateResponse> Templates { get; set; }

        /// <summary>
        /// Gets or Sets Paging
        /// </summary>
        [DataMember(Name = "paging", IsRequired = true, EmitDefaultValue = true)]
        public WhatsappPagination Paging { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WhatsappListTemplatesResponse {\n");
            sb.Append("  Templates: ").Append(Templates).Append("\n");
            sb.Append("  Paging: ").Append(Paging).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
